### ISSUE TITLE
MultiReg issue

### ISSUE THREAD

**Issue by jimmymagemtek** [enjoy-digital/litex#1014]
Hi Sir,
I know that "MultiReg" works for the sync from higher ClockDomain to lower one:

self.specials += MultiReg( input_domainA, output_domainB, "pix" )

domainA: high
domainB: low

But how about the reverse direction ?
Vivado fails to compile it.

Please advise. Thanks.

Jimmy

**Comment by alanvgreen** [comment]
What error does Vivado give?

**Comment by enjoy-digital** [comment]
Closing since no feedback.
