### ISSUE TITLE
comm_pcie: Update mmap?

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litex#1026]
It seems the Python's mmap API has changed and comm_pcie has to be updated: https://bugs.python.org/issue40785

**Comment by sajattack** [comment]
My problem actually went away when I simply unloaded the litepcie driver, even with the mmap at 0.

**Comment by enjoy-digital** [comment]
Thanks for the feedback @sajattack, so this was not related to a different Python version.
