### ISSUE TITLE
Cores not building up other than "vexriscv"

### ISSUE THREAD

**Issue by zeeshandildar-lm** [enjoy-digital/litex#1034]
I have tried to build "serv" and "picorv32" but failed due to recent commits, however there was no issue in building "vexriscv". After checking out to previous hash one by one it was found that since commit "aff2aefa724a76ccaa7637c94e314e0aedbad5df" this problem arose. kindly look into this issue.
![issue](https://user-images.githubusercontent.com/72376312/133046676-accf4a10-d581-4f2b-9d00-baa955150baa.png)

**Comment by enjoy-digital** [comment]
Thanks @zeeshandildar-lm for the feedback, the issue was introduced when adding SPI Flash support. This is fixed with https://github.com/enjoy-digital/litex/commit/cb7b0f44cfe2045a1337fdf518326bb14c421b6e.
