### ISSUE TITLE
Add TinyFPGA EX support

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litex#105]
- [x] Verify ECP5 diamond build support. 
- [ ] Verify programmer support.
- [ ] Create or reuse HyperRAM core.
- [ ] Port LiteSDCard to ECP5. (adapt primitives).

**Comment by mithro** [comment]
Does it make sense for HyperRAM to be part of LiteDRAM in some way?

Links to HyperRAM cores;
 - https://github.com/blackmesalabs/hyperram
 - https://github.com/gtjennings1/HyperRAM

**Comment by enjoy-digital** [comment]
Transfered to https://github.com/litex-hub/litex-boards/issues/14, we now have an HypeRam core we can use for the TinyFPGA EX directly in LiteX: https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/hyperbus.py
