### ISSUE TITLE
riscv64-unknown-gcc toolchain version 10.2.0-2020.12.8-x86_64-linux-centos error

### ISSUE THREAD

**Issue by aghaali-rs** [enjoy-digital/litex#1059]
I am using RISCV64 GCC toolchain version 10.2.0-2020.12.8 for centos 7. I was initially at commit 694878a35a2f792ad195ff9c585d689467a76b1d which worked fine however I recently switched to commit cb6861e1c81e154b953d33b69d2fe1490195185d and now i get the error in the attached screenshot.

![toolchain error litex](https://user-images.githubusercontent.com/87408268/136157587-51e47baa-2d50-4964-87c0-31ed125980f1.png)
.
I am using a prebuild from https://github.com/sifive/freedom-tools/releases 
However, when using version 8.3.0-2019.08.0 for Linux it works fine on centos 7.

**Comment by aghaali-rs** [comment]
A fresh install of LiteX and a fresh download of the prebuilt toolchain result in the error seen in the attached screenshot.
![fresh build error](https://user-images.githubusercontent.com/87408268/136184766-4a87e594-a1b6-47b5-a364-95578345dede.png)

**Comment by akioolin** [comment]
Hi, 

In my current system. the SiFive prebuild gnu cross gcc toolchain 10.1.0 could work very well in CFU-Playground which is enabled picolibc support. 

https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.08/riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-ubuntu14.tar.gz

BR, Akio

**Comment by aghaali-rs** [comment]
I tried the following four different versions of the toolchain:

- riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-centos6
- riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14
- riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-centos6
- riscv64-unknown-elf-gcc-10.1.0-2020.08.2-x86_64-linux-ubuntu14

Out of these four versions both 10.2.0 versions (centos6 and ubuntu14) had the same error however both 10.1.0 versions are working fine.

**Comment by enjoy-digital** [comment]
The issue seems related to the 10.2 toolchain and a working toolchain should be used.
