### ISSUE TITLE
Documentation flag "--doc" not working

### ISSUE THREAD

**Issue by zeeshandildar-rs** [enjoy-digital/litex#1150]
I was trying to generate document along with the soc but unfortunately "--doc" is not working at the recent commit " f04a3dcc50aab46a86067b04bf2eb9284cd3a89d". Kindly resolve this issue as soon as possible.

**Comment by enjoy-digital** [comment]
This is still working correctly here. Issue with Python 3.10 has been reported on IRC, which version of Python are you using? (LiteX hasn't  been tested with 3.10 yet).

**Comment by zeeshandildar-rs** [comment]
I am using python version 3.6.8

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by enjoy-digital** [comment]
OK, sorry I'm not able to help with the provided information. Please have a look at https://github.com/enjoy-digital/litex/wiki/Feedback-Contribution-Support#how-to-create-an-issue-when-it-does-not-work and provide the minimal information required to be able to help/reproduce.

**Comment by zeeshandildar-rs** [comment]
I have cloned the litex github repository and build the soc using following command:
`lxsim --cpu-type=serv --doc`
It successfully built the soc but there is not "doc" directory in "/build/sim/" so I can't see the documentation generated along with this soc.

**Comment by enjoy-digital** [comment]
`lxsim --cpu-type=serv --no-compile-gateware --doc` correctly generates the doc on my machine, can you test this? If not I'll need to build logs.

**Comment by zeeshandildar-rs** [comment]
Yes it is working now. So, it is compulsory to add --no-compile-gateware along --doc. right?

**Comment by enjoy-digital** [comment]
The documentation can only be created once the SoC has been build. So in simulation we either have to avoid running the simulation (`--no-compile-gateware`) or run it but do a CTRL+C to interrupt it to generate the doc.
