### ISSUE TITLE
yosys+nextpnr toolchain: instantiation of FD primitives should be avoided

### ISSUE THREAD

**Issue by suarezvictor** [enjoy-digital/litex#1182]
They seems not required, anyways.
In particular, when not using such toolchain the following warnings are raised:

Test command:
`./digilent_arty.py --sys-clk-freq=50e6 --integrated-main-ram-size=8192 --cpu-type=femtorv --toolchain=yosys+nextpnr --build`

```
WARNING: [DRC PLHOLDVIO-2] Non-Optimal connections which could lead to hold violations: A LUT clk100_inst is driving clock pin of 8 cells. This could lead to large hold time violations. Involved cells are:
FD, FD_1, FD_2, FD_3, FD_4, FD_5, FD_6, and FD_7
```

**Comment by enjoy-digital** [comment]
Thanks @suarezvictor for reporting, @trabucayre just fixed it with https://github.com/enjoy-digital/litex/pull/1183.
