### ISSUE TITLE
cv32e41p - Prompt not answering

### ISSUE THREAD

**Issue by pcotret** [enjoy-digital/litex#1200]
Still working on porting the [cv32e41p](https://github.com/openhwgroup/cv32e41p). LiteX boots but the prompt doesn't answering (when `litex_sim --cpu-type=cv32e41p`)...
 
![litex_prompt](https://user-images.githubusercontent.com/404135/152683538-5653234f-73b6-45be-b8df-390483378abe.gif)

- As everything boots, I assume hardware connections to the core are OK.
- The prompt blinks but doesn't print anything from my keyboard.

What could be the problem?
Something related to interrupts maybe?  (`litex/bios/isr` has been modified).

**Comment by mithro** [comment]
My guess would be interrupts too...

**Comment by enjoy-digital** [comment]
@pcotret: To confirm it's related to interrupts, can you add `self.add_constant("UART_POLLING")` to your SoC? It will switch the UART to polling mode (as we are doing for CPUs not supporting interrupts: https://github.com/enjoy-digital/litex/blob/8f5d9714917cedc7c39b440357380cd4463b9b4d/litex/soc/integration/soc.py#L1253).

**Comment by pcotret** [comment]
As I'm using the `litex_sim` binary, I've added a flag in my `core/cv32e41p/core.py` : 
```diff
    # GCC Flags.
    @property
    def gcc_flags(self):
        flags = GCC_FLAGS[self.variant]
        flags += "-D__cv32e41p__ "
+       flags += f" -DUART_POLLING"
 ```
![Screencast 2022-02-08 09 38 05](https://user-images.githubusercontent.com/404135/152949361-4d327b46-48f0-4644-ac57-0afb4f7e895e.gif)

So, if I understand correctly, guilty part is related to interrupts?

**Comment by enjoy-digital** [comment]
@pcotret: If it's working correctly when defining `UART_POLLING` the issue is indeed related to interrupts.

**Comment by pcotret** [comment]
![image](https://user-images.githubusercontent.com/404135/153602383-beab4c89-259e-42d3-bdb6-6e909a347bf8.png)

Found my issue!
In fact, the UART interrupt was mapped on read-only bits in related CSRs...
