### ISSUE TITLE
CV32E40P  REPL And RESC files for renode simulator 

### ISSUE THREAD

**Issue by mohamedElbouazzati** [enjoy-digital/litex#1206]
Hi litex community, 

I am working with RISC-V cv32e40p on litex_sim and I want to simulate a node on a renode. I followed the following steps to produce the renode' files and got this error.

**Steps:**
`litex_sim --cpu-type cv32e40p --csr-json csr.json`
`litex_json2renode csr.json  --resc litex.resc --repl litex.repl --bios-binary build/sim/software/bios/bios.bin`

**Error:**
```
Skipping io region: csr
Traceback (most recent call last):
  File "/home/med/.local/bin/litex_json2renode", line 33, in <module>
    sys.exit(load_entry_point('litex', 'console_scripts', 'litex_json2renode')())
  File "/home/med/Desktop/workflow/litex/litex/tools/litex_json2renode.py", line 874, in main
    print_or_save(args.repl, generate_repl(csr, etherbone_peripherals, args.autoalign_memor_regions))
  File "/home/med/Desktop/workflow/litex/litex/tools/litex_json2renode.py", line 565, in generate_repl
    result += generate_cpu(csr, time_provider)
  File "/home/med/Desktop/workflow/litex/litex/tools/litex_json2renode.py", line 257, in generate_cpu
    raise Exception('Unsupported cpu type: {}'.format(kind))
Exception: Unsupported cpu type: cv32e40p
```
is there any possibility to add cv32e40p to this file` litex_json2renode.py` ?

Any help, thanks a lot

**Comment by mithro** [comment]
@mateusz-holenko / @PiotrZierhoffer - I think Renode supports emulation of `cv32e40p`?

**Comment by mithro** [comment]
The release notes @ https://renode.io/news/Renode-1.12-release/ say "OpenHW Group’s CV32E40P-based RISC‑V platform with many PULP peripherals"/

**Comment by PiotrZierhoffer** [comment]
That's correct. We'll add it to `litex_json2renode`

**Comment by mohamedElbouazzati** [comment]
@mithro Yes, but want to simulate it with another tracer block that's why i'm using litex first

**Comment by mohamedElbouazzati** [comment]
@PiotrZierhoffer will the changes be only on litex_json2renode.py or also on the other litex tools?

**Comment by PiotrZierhoffer** [comment]
There are some changes to https://github.com/enjoy-digital/litex/pull/1230 that you can check. They affect this script only.
