### ISSUE TITLE
Reading QSPI Flash using mem_read on AC701

### ISSUE THREAD

**Issue by maninigaur** [enjoy-digital/litex#1210]
I have modified the scripts litex-boards/targets/xilinx_ac701.py and litex-boards/platforms/xilinx_ac701.py to include the SPI flash functionality in Quad SPI mode. Here are my questions:
1. As I understand, Litex configures Quad SPI in the 4x mode and since I am using AC701 board, I hope to get the read and write operations working for Quad SPI. Are these supported by Litex, as in will I be able to read Quad SPI flash using mem_read if I have written on it using some other tool like Open OCD?
2. In order to write on the QSPI flash (N25Q256A13ESF40G- Micron) of AC701 board, I am using the proxy bitstream generated by 
[this]( https://github.com/quartiq/bscan_spi_bitstreams/blob/master/xilinx_bscan_spi.py) script using OpenOCD.
 In your experience, is it capable of writing on the QSPI flash? If data is written in this manner, will we be able to read it on Litex using mem_read?

**Comment by enjoy-digital** [comment]
Hi @maninigaur,

you'll should indeed be able to do a `mem_list` to list the memory regions of the SOC and then a `mem_read` on the SPI Flash region. If a bitstream if configured through OpenOCD in the SPI Flash, you should be able to read and recognize it.

The OpenOCD proxy bitstreams are working fine on Artix7 yes, you can use it to write to the SPI Flash and then exercise mem_read.

If SPI Flash support is working correctly on the AC701,  could you contribue it to LiteX-Boards repository?  :)
I also need to do some tests on AC701 with the DDR3, so if you have troubles with the SPI Flash I could also have a look.

**Comment by enjoy-digital** [comment]
https://github.com/litex-hub/litex-boards/commit/9914478854b83ec5750c07df995b2390977280c2 adds support for SPI-Flash on the AC701. I think we can now close this since support has been added and question answered.
