### ISSUE TITLE
CI workflow does not test litex_setup.py

### ISSUE THREAD

**Issue by kaolpr** [enjoy-digital/litex#1219]
While looking at CI run for #1218 I've noticed that "Install LiteX" step [uses `litex_setup.py` from current master](https://github.com/enjoy-digital/litex/blob/82daa48e09ae91c97d1a412f85643caa704a1a1c/.github/workflows/ci.yml#L27). It may be beneficial to use the script from the tested codebase instead.

**Comment by enjoy-digital** [comment]
Thanks @kaolpr, this is now the case with https://github.com/enjoy-digital/litex/pull/1249. I started working on https://github.com/enjoy-digital/litex/pull/1218 and will continue soon.
