### ISSUE TITLE
Bare Metal Demo  --build-path ignored in Makefile BUILD_DIR

### ISSUE THREAD

**Issue by mzau** [enjoy-digital/litex#1299]
First of all the instructions for the in README.md should be

```
python3 -m litex_boards.targets.digilent_arty --build --load
litex_bare_metal_demo --build-path=build/digilent_arty
```
(instead of --build-path=build/arty)

But the `BUILD_DIR`  isn't set to the  `--build-path`. A workaround for me is to change the BUILD_DIR in  [Makefile](https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/demo/Makefile) to
`BUILD_DIR?=../build/digilent_arty`. 
I think there is some macro definition missing, which inserts the correct board name into the Makefile?

**Comment by mzau** [comment]
works correct with  `litex_bare_metal_demo --build-path build/digilent_arty` - no '=' after --build-path.

**Comment by enjoy-digital** [comment]
Thanks @mzau, the README has been updated with https://github.com/enjoy-digital/litex/commit/f16f8e5f9ea1dd215c8fc4fc3a489738ab843fb5. A space should be equivalent to an equal after `--build-path`. Python 3.8.10 here has no problem parsing it, which version of Python are you using?

**Comment by mzau** [comment]
>  Python 3.8.10 here has no problem parsing it, which version of Python are you using?
Thanks!  I still have Python 3.6. I will change it.
