### ISSUE TITLE
litex_sim ignores --csr-csv parameter

### ISSUE THREAD

**Issue by Shatur** [enjoy-digital/litex#1348]
**Description**

`litex_sim --help` says the following:

```
...
  --csr-csv CSR_CSV
          Write SoC mapping to the specified CSV file. (default: None)
...
```

So I would expect that by default it doesn't generate everything and allows to override this setting.

**Actual behavior**

But running `litex_sim` command without any arguments produces `csr.csv` file in the current working directory.
And setting `--csr-csv` doesn't have any effect: `litex_sim --csr-csv=custom_location.csv` produces only file named `csr.csv`.

**Comment by dayjaby** [comment]
Same issue also in litex_client with a PR already open: https://github.com/enjoy-digital/litex/pull/927

**Comment by Shatur** [comment]
Looks like @enjoy-digital already implemented it for `litex_client` :)

**Comment by enjoy-digital** [comment]
Thanks @Shatur, this is fixed with https://github.com/enjoy-digital/litex/commit/a285071154c41a3d5777224eb97f948e65218f24.
