### ISSUE TITLE
Analog video output needs a baseline on sync 

### ISSUE THREAD

**Issue by suarezvictor** [enjoy-digital/litex#1349]
VGA monitors seem to DC filter the analog values, so instead of interpreting 0V as black, the interpret the minimum color values as black. Thus, on blanking time, the analog output should go to zero. If not, a solid color (first figure, cyan signal) would be interpreted as a black value but with just a DC offset, producing the second picture:

![image](https://user-images.githubusercontent.com/8551129/176550652-af06ed16-2c6d-4579-a018-e5ef9cacb0cb.png)

![image](https://user-images.githubusercontent.com/8551129/176550599-1f19d932-5851-4094-8de4-42cc17b50cfd.png)

PATCH:
It needs just to make zero the analog values on the blanking times, using the `sink.de` signal.
Replace https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/video.py#L719 with this:
```
        if hasattr(pads, "hsync_n"):
            self.specials += SDROutput(i=~sink.hsync, o=pads.hsync_n, clk=ClockSignal(clock_domain))
        else:
            self.specials += SDROutput(i=sink.hsync,  o=pads.hsync,   clk=ClockSignal(clock_domain))

        if hasattr(pads, "vsync_n"):
            self.specials += SDROutput(i=~sink.vsync, o=pads.vsync_n, clk=ClockSignal(clock_domain))
        else:
            self.specials += SDROutput(i=sink.vsync,  o=pads.vsync,   clk=ClockSignal(clock_domain))

        # Drive Datas.
        cbits  = len(pads.r)
        cshift = (8 - cbits)
        for i in range(cbits):
            self.specials += SDROutput(i=sink.r[cshift + i] & sink.de, o=pads.r[i], clk=ClockSignal(clock_domain))
            self.specials += SDROutput(i=sink.g[cshift + i] & sink.de, o=pads.g[i], clk=ClockSignal(clock_domain))
            self.specials += SDROutput(i=sink.b[cshift + i] & sink.de, o=pads.b[i], clk=ClockSignal(clock_domain))
```
As can be appreciated, the code also allows for vertical & horizontal sync to be negative or positive, independently.

**Comment by enjoy-digital** [comment]
Thanks @suarezvictor! This has been applied with https://github.com/enjoy-digital/litex/commit/ee580f2ce8adce2417fe1cd41ddb1a61d73098b2.
