### ISSUE TITLE
Help adding Wishbone module

### ISSUE THREAD

**Issue by LesserWorks** [enjoy-digital/litex#1368]
I've browsed a lot of the Litex and Linux-on-LitexVexRiscv code that uses a wishbone bus but I'm still quite lost about how to connect my own peripheral to the system bus, and then access it from software. Would anyone be able to provide some advice or maybe a small example? Thank you for your time.

**Comment by LesserWorks** [comment]
Okay I made a small Wishbone module in litex/soc/cores/:
```
from migen import *
from litex.soc.interconnect.csr import *
from litex.soc.interconnect import wishbone

class WishboneTest(Module, AutoCSR):
    def __init__(self,platform):
        self.bus = bus = wishbone.Interface()

        self.sync += [
            If((bus.adr & 1) == 0,
                bus.dat_r.eq(0x45454545)
            ).Elif((bus.adr & 1) == 1,
                bus.dat_r.eq(0xABABABAB)
            ),

            bus.ack.eq(0),
            If(bus.cyc & bus.stb & ~bus.ack,
                bus.ack.eq(1)
            )
        ]
```
And I added the following lines to linux-on-litex-vexriscv/soc_linux.py:
```
def add_wishbonetest(self):
            self.submodules.wbtest = WishboneTest(self.platform)
            self.add_memory_region("wbtest", None, 0x1000, type="io")
            self.add_wb_slave(self.bus.regions["wbtest"].origin, self.wbtest.bus, 0x1000)
```
(and a corresponding function call in linux-on-litex-vexriscv/make.py).
With this, once Linux boots on the Arty A7, I am able to access access the WishboneTest module as expected with software memory accesses, however the ethernet module doesn't work. During the Linux boot it says `Starting network: [   13.141454] liteeth f0002800.mac eth0: LITEETH_READER_READY not ready`. The ethernet works if the WishboneTest module is not present. Do you know what the problem could be?

**Comment by LesserWorks** [comment]
Since it might be helpful for others, I got it to work with the following "Hello world" wishbone slave:
```python
from migen import *
from litex.soc.interconnect import wishbone

class WishboneTest(Module):
    def __init__(self, platform):
        self.bus = bus = wishbone.Interface()
        data = Signal(bits_sign=32, reset = 0x45454545)

        self.sync += [
            If((bus.adr & 0b111) == 0,
                bus.dat_r.eq(data)
            ).Elif((bus.adr & 0b111) == 1,
                bus.dat_r.eq(0xABABABAB)
            ),
            bus.ack.eq(0),
            If(bus.cyc & bus.stb & ~bus.ack,
                bus.ack.eq(1),
                If(bus.we,
                    If((bus.adr & 0b111) == 2,
                        data.eq(bus.dat_w)
                    )
                )
            )
        ]
```
And then adding the following function to `linux-on-litex-vexriscv/soc_linux.py`
```python
def add_wishbonetest(self):
    mem_len = 0x100 # Size of address space for this wishbone module
    self.submodules.wbtest = WishboneTest(self.platform)
    self.add_memory_region("wbtest", None, mem_len, type="io")
    self.add_wb_slave(self.bus.regions["wbtest"].origin, self.wbtest.bus, mem_len)
```
and calling the function from `make.py`.

**Comment by enjoy-digital** [comment]
Hi @LesserWorks,

Great and thanks a lot for sharing your code. I'll make sure that we integrate a such example in the wiki!
