### ISSUE TITLE
Undefined refrence to C liberaries

### ISSUE THREAD

**Issue by FATHY174** [enjoy-digital/litex#1370]
Hello @enjoy-digital,
I have tried before using the function clock()  (which is a built in function in C libraries) it gives me `undefined reference to clock()`
also, I have tried generating CSV file to get my outputs out of a C file in memtest.c file but it also gives me : 
`/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/picolib/picosbrk.c:49: undefined reference to `__heap_end'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: ../libc/libc.a(libc_picolib_picosbrk.c.o):/home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/picolib/picosbrk.c:41: undefined reference to `__heap_start'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: ../libc/libc.a(libc_tinystdio_fopen.c.o): in function `fopen':
/home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fopen.c:51: undefined reference to `open'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: ../libc/libc.a(libc_tinystdio_fdopen.c.o): in function `fdopen':
/home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:56: undefined reference to `close'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `read'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `read'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `write'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `write'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `lseek'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `lseek'
/home/fathymd/litex2/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-centos6/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /home/fathymd/litex2/litex-boards/litex_boards/targets/build/xilinx_vc707/software/libc/../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/tinystdio/fdopen.c:62: undefined reference to `close'
`

So, can someone tell me what is the linkage problem I am doing?

**Comment by enjoy-digital** [comment]
Hi @FATHY174,

please provide a minimal repro. 

Thanks.

**Comment by enjoy-digital** [comment]
Closing since no feedback/update.

**Comment by jwfaye** [comment]
Hello, I encounter the same error on a code that was working fine. Is there any news about this issue ? I try to compile some C code to run on a dual core architecture but I have the same error.

**Comment by jwfaye** [comment]
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : ./obj/main.o : dans la fonction « main » :
/home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:175 : référence indéfinie vers « __truncdfsf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:176 : référence indéfinie vers « __extendsfdf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:196 : référence indéfinie vers « __truncdfsf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:199 : référence indéfinie vers « __extendsfdf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:206 : référence indéfinie vers « __truncdfsf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:207 : référence indéfinie vers « __extendsfdf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:225 : référence indéfinie vers « __truncdfsf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/sw/firmwares/config_1_8/core_1_firmware/main.c:226 : référence indéfinie vers « __extendsfdf2 »
/usr/lib/gcc-cross/riscv64-linux-gnu/11/../../../../riscv64-linux-gnu/bin/ld : /home/jofaye/Documents/work/computer_architecture/AES_SVM/hw/build/firev_soc/software/libc/libc.a(libc_ssp_chk_fail.c.o) : dans la fonction « __chk_fail » :
/home/jofaye/Documents/work/computer_architecture/AES_SVM/hw/build/firev_soc/software/libc/../../../../../../../../../../../opt/litex_root/pythondata-software-picolibc/pythondata_software_picolibc/data/newlib/libc/ssp/chk_fail.c:13 : référence indéfinie vers « write »

**Comment by FATHY174** [comment]
@jwfaye to add any external C file you need to add it in the Makefile to generate .o files in the generated design to be able to integrate it in Litex design.

Error you sent I am not sure, but I think is because you are using double or float variables. if it is you need to enable using float from Picolibc you can look at :
1- https://keithp.com/blogs/picolibc-float/
2- https://github.com/picolibc/picolibc/blob/main/doc/build.md

Hope it is helpful.
