### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by FATHY174** [enjoy-digital/litex#1382]
Hello @enjoy-digital 

I just want to know why printing any float number in the C codes gives the output `*float*` or even gives `undefined reference to `__extendsfdf2'` is there any library I should include or there is something I don't get?

**Comment by FATHY174** [comment]
@enjoy-digital 
adding something like this to any C file:
`double uu = 5.9;

	int kkk =3;
        printf("\nuu = %f\n",uu);
        double ll = 2.9;
        printf("\nll = %f\n",ll);
        double tt = (uu*(double)kkk)/ll;
        printf("\ntt = %f\n",(uu*(double)kkk)/ll);
        printf("\ntt dec = %d\n",(int)((uu*(double)kkk)/ll));`

gives :
`uu = *float*'
ll = *float*'
rtt = *float*`

what's the reason??

**Comment by FATHY174** [comment]
I found the problem is related to the PICOLIBC :
flags for floating should be enabled

**Comment by enjoy-digital** [comment]
Good @FATHY174, would you mind sharing the solution? We'll try to integrate it.

**Comment by tcal-x** [comment]
I had always assumed that `printf` `%f`/`%d` support was left out for reasons of code size, and that's why you'd do something simple if you needed one or two decimals of accuracy, as here: https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/libbase/memtest.c#L168-L177 .

But yes it would be nice to have an option for having floats directly supported by printf!

**Comment by befedo** [comment]
Hi there,

I'm also looking for a way to `printf` floats (using the XADC module) and reading through the [picolibc doc](https://github.com/picolibc/picolibc/blob/main/doc/printf.md) doesn't seem to work. Setting `PICOLIBC_FLOAT_PRINTF_SCANF` also yields `*float*`. Any hints on how to solve this?

Thanks for your time and best regards
befedo

**Comment by befedo** [comment]
> Hi there,
> 
> I'm also looking for a way to `printf` floats (using the XADC module) and reading through the [picolibc doc](https://github.com/picolibc/picolibc/blob/main/doc/printf.md) doesn't seem to work. Setting `PICOLIBC_FLOAT_PRINTF_SCANF` also yields `*float*`. Any hints on how to solve this?
> 
> Thanks for your time and best regards befedo

Found it ... one could use
```
CFLAGS += -Wl,--defsym=vfprintf=__d_vfprintf -Wl,--defsym=vfscanf=__d_vfscanf
```
don't know why `PICOLIBC_FLOAT_PRINTF_SCANF` isn't sufficient.
