### ISSUE TITLE
[Request] Setup GitHub Discussions?

### ISSUE THREAD

**Issue by francis2tm** [enjoy-digital/litex#1394]
Hello,
I feel many times the need of having a forum like stackoverflow for questions related to litex. This are a bit different than an issue, so I think it'd be a great addition to the Litex community! https://docs.github.com/pt/discussions/quickstart.

PS: I replied to an issue already closed: #1112

**Comment by enjoy-digital** [comment]
Hello @francis2tm,

I'll think about it. For now you can re-open closed issues if you want to discuss things further.

**Comment by francis2tm** [comment]
Hello @enjoy-digital ,
Thanks for the switft reply. However, I can't reopen #1112.

**Comment by francis2tm** [comment]
Thanks!
