### ISSUE TITLE
Malicious wiki edit

### ISSUE THREAD

**Issue by dayjaby** [enjoy-digital/litex#1398]
The permissions for editing the wiki seem to be a bit too permissive:

https://github.com/enjoy-digital/litex/wiki/Installation/_compare/c797cc2%5E...c797cc2

**Comment by enjoy-digital** [comment]
Thanks a lot @dayjaby! I changed the permission to edit to collaborators only and should have gave collaborator accesses to previous contributors of the wiki. Developers interested to contribute can contact me to get access.
