### ISSUE TITLE
Axi_Stream missing TID and TDEST from the standard interface

### ISSUE THREAD

**Issue by bilalahmed-RS** [enjoy-digital/litex#1419]
Axi_stream.py is missing 'tid' and 'tdest' signal as per the standard AMBA 4 AXI4-Stream Protocol.

**Comment by enjoy-digital** [comment]
Thanks @bilalahmed-RS, I'll add it.

**Comment by enjoy-digital** [comment]
Added with https://github.com/enjoy-digital/litex/commit/afc89c9350f3d6c4f0983fe863e03accc1ed9a8c.
