### ISSUE TITLE
Addition of TDEST_WIDTH parameter for TDEST signal in AXI_Stream. 

### ISSUE THREAD

**Issue by bilalahmed-RS** [enjoy-digital/litex#1420]
Once 'tdest' signal is added to the interface, parameter for this should be incorporated.

**Comment by enjoy-digital** [comment]
Thanks @bilalahmed-RS, this will be added while looking at https://github.com/enjoy-digital/litex/issues/1419.

**Comment by enjoy-digital** [comment]
Added with https://github.com/enjoy-digital/litex/commit/afc89c9350f3d6c4f0983fe863e03accc1ed9a8c.
