### ISSUE TITLE
Unable to compile for Max10 with Quartus Prime 21.1 Lite - PLL error "inclk[0] ... must be driven by a non-inverted input pin or another PLL"

### ISSUE THREAD

**Issue by p-kraszewski** [enjoy-digital/litex#1455]
Hello!

# Message

I'm trying to compile demo code for `trenz_max1000.py`. Compilation fails with the following error:

```
[...]

Info (16010): Generating hard_block partition "hard_block:auto_generated_inst"
    Info (16011): Adding 1 node(s), including 0 DDIO, 1 PLL, 0 transceiver and 0 LCELL
Error (15065): Clock input port inclk[0] of PLL "altpll:ALTPLL|altpll_sl21:auto_generated|pll1" must be driven by a non-inverted input pin or another PLL, optionally through a Clock Control block File: /.../LiteX/litex-boards/litex_boards/targets/build/trenz_max1000/gateware/db/altpll_sl21.tdf Line: 28
    Info (15024): Input port INCLK[0] of node "altpll:ALTPLL|altpll_sl21:auto_generated|pll1" is driven by clk12~buf0 which is COMBOUT output port of Combinational cell type node clk12~buf0 File: /.../LiteX/litex-boards/litex_boards/targets/build/trenz_max1000/gateware/db/altpll_sl21.tdf Line: 28
Error: Quartus Prime Analysis & Synthesis was unsuccessful. 1 error, 372 warnings
    Error: Peak virtual memory: 648 megabytes
    Error: Processing ended: Sun Oct  9 17:57:33 2022
    Error: Elapsed time: 00:00:15
    Error: Total CPU time (on all processors): 00:00:21
[...]
```

# Environment:

* **LiteX**: installed via `./litex_setup.py --init --install --user`
* **OS**: `Manjaro`, up-to date
* **FPGA toolchain**: `Version 21.1.1 Build 850 06/23/2022 SJ Lite Edition`, working correctly, I am able to compile and burn reference projects
* **RiscV toolchain**: `gcc 12.2.0 "riscv64-elf-gcc (Arch Linux Repositories) 12.2.0"`

The exact error is repeated for `litex-2021.04-1` from the official Manjaro repository.

**Comment by enjoy-digital** [comment]
This is fixed with https://github.com/enjoy-digital/litex/commit/62e869296f14fcae9e27f9b3edf7b5c05fe82af1 and https://github.com/enjoy-digital/litex/commit/c1885b333fbf607aa111b817dec9b8c7d85c3b92.
