### ISSUE TITLE
Define timer logic in demo app

### ISSUE THREAD

**Issue by YiminGao0113** [enjoy-digital/litex#1461]
I want to ask if there are any tips or tutorials to define a timer logic in the c code of demo app. How do I utilize the timer in the SoC in C code? This might be an easy question but I am kind of new to embedded. Any help would be appreciated, thanks!

**Comment by cklarhorst** [comment]
You can find an example how the timer can be used here: https://github.com/enjoy-digital/litex/blob/808cf1a4660c448d514d0c9c277096db4eac4622/litex/soc/software/libbase/memtest.c#L281-L309
