### ISSUE TITLE
trellis builder needs to take package type as well

### ISSUE THREAD

**Issue by tinyfpga** [enjoy-digital/litex#147]
The Lattice trellis builder needs to take in the package type as well. I'll see if I can't create a pull request for this.

**Comment by enjoy-digital** [comment]
@tinyfpga: i'm not sure to understand what is missing, do you have more information?

**Comment by enjoy-digital** [comment]
Sorry, i figured out. That's implemented with: https://github.com/enjoy-digital/litex/commit/5ef28bdf75a57735312a37d444919a371b69daae.
