### ISSUE TITLE
Bug litex_cli --write 

### ISSUE THREAD

**Issue by duqiang** [enjoy-digital/litex#1534]
It seems like there is a bug at [litex_client.py](https://github.com/enjoy-digital/litex/blob/78fbb64c18cd92e3ae07fd1e1498dcab91590cf7/litex/tools/litex_client.py#L406) where the `reg2addr()` missed the first argument of `host`, when it was supposed to do so at commit [dccdc23](https://github.com/enjoy-digital/litex/commit/dccdc236a669359ffc525e03e6be9d7b7a65d6b8).

**Comment by enjoy-digital** [comment]
Thanks @duqiang for reporting, this is fixed with https://github.com/enjoy-digital/litex/commit/cb85a8caf1fd150d7a9563e71f553d931157abff.
