### ISSUE TITLE
Run a simple c program under litex_sim

### ISSUE THREAD

**Issue by yicwang** [enjoy-digital/litex#1542]
Hi @enjoy-digital,

I am very new to this project, and just started to play with it. I am now able to run the simulator and successfully get into the "litex>" prompt, and I am going to run a simple C hello world. I complied the code with riscv64-unknown-elf-gcc, and have something like foo.bin. The document points me to use serial port (litex_term utility) to upload  the image, but this utility requires a "real" serial port under /dev. With the simulator what do I give over there? How should I upload and run a simple hello world post getting the "litex>" prompt successfully?

Thanks very much!

Regards,
Yichen

**Comment by enjoy-digital** [comment]
Hi @yicwang,

the simulation doest not use litex_term. To do what you want in simulation, you can have a look at: https://github.com/enjoy-digital/litex/wiki/SoC-Simulator

**Comment by yicwang** [comment]
Perfect, that is all I want!!! Thanks very much!
