### ISSUE TITLE
Added video simulation

### ISSUE THREAD

**Issue by suarezvictor** [enjoy-digital/litex#1562]
It emulates video hardware right from hsync, vsync, de and the RGB signals, detecting the resolution automatically.

Sources on my fork: https://github.com/enjoy-digital/litex/commit/dab5291fb61bbecc87725c427585f45d7993a4d0 and https://github.com/enjoy-digital/litex/commit/777fc2663b291d602ddfcb62d0a855f1cc8e4bdd

![image](https://user-images.githubusercontent.com/8551129/211811809-71aa462f-d1ef-415e-8480-18f846fd69a7.png)

**Comment by enjoy-digital** [comment]
Nice! Thanks @suarezvictor; I'll have a closer look at it soon; this would be great to integrate it since could be useful for various use-cases.

**Comment by mithro** [comment]
Super cool!
