### ISSUE TITLE
liblitedram accessors change causes build failure on ecp5 boards

### ISSUE THREAD

**Issue by gsomlo** [enjoy-digital/litex#1583]
Some combination of commit 58fda1a3 ("liblitedram: Move PHY accessors to a separate file") and/or commit 4c605020 ("liblitedram: Codebase cleanup") result in a failure to build on ecp5 boards (tested on trellisboard and ecpix5):

```
riscv64-unknown-elf/bin/ld: ../liblitedram/liblitedram.a(accessors.o): in function `write_inc_dq_bitslip':
/litex/litex/soc/software/liblitedram/accessors.c:116: undefined reference to `ddrphy_wdly_dq_bitslip_write'
riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: ../liblitedram/liblitedram.a(accessors.o): in function `write_rst_dq_bitslip':
/litex/litex/soc/software/liblitedram/accessors.c:122: undefined reference to `ddrphy_wdly_dq_bitslip_rst_write'
collect2: error: ld returned 1 exit status
```

From a cursory analysis it appears that the new conditional:

```
+#if defined(SDRAM_PHY_BITSLIPS)
```

doesn't adequately cover the conditions existent on ecp5 boards, whereas the old one:

```
-#if defined(SDRAM_PHY_WRITE_LATENCY_CALIBRATION_CAPABLE) || defined(SDRAM_BITSLIP_CAPABLE)
```

did. Test/debug using the following command line:

```
litex-boards/litex_boards/targets/lambdaconcept_ecpix5.py --build --cpu-type vexriscv
```

The cpu type doesn't really matter, it's the conditional compilation of accessors depending on register accessors generated in `build/lambdaconcept_ecpix5/software/include/generated/csr.h` that appears to be the problem.

@mtdudek @michalsieron @enjoy-digital -- can you double-check the `#ifdef` magic changes acrosss these commits? Thanks!

**Comment by enjoy-digital** [comment]
Thanks @gsomlo for the feedback, this should be fixed with https://github.com/enjoy-digital/litex/commit/a6d9955c9d3065d5c04cd4cba392b2fcb831380f. (Just tested compilation and bistream on a Trellisboard).
