### ISSUE TITLE
Unable to use video terminal included with default target for tang-primer-20k

### ISSUE THREAD

**Issue by L-jr-Bennett** [enjoy-digital/litex#1622]
The following is spit out and fails to build, I've attempted to set the leds to use same io type in the platform.py file but still fails

/build/sipeed_tang_primer_20k/gateware/sipeed_tang_primer_20k.cst"
ERROR  (CT1136) : Bank 1 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'led0_obuf' : IO_TYPE = LVCMOS33 in the same bank
ERROR  (CT1136) : Bank 1 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'led1_obuf' : IO_TYPE = LVCMOS33 in the same bank
ERROR  (CT1136) : Bank 1 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'led2_obuf' : IO_TYPE = LVCMOS33 in the same bank
ERROR  (CT1136) : Bank 1 vccio(1.8) is locked by other constraint or embedded port, conflicting BANK_VCCIO set by 'led3_obuf' : IO_TYPE = LVCMOS33 in the same bank

**Comment by enjoy-digital** [comment]
Fixed with https://github.com/litex-hub/litex-boards/commit/9e73ba53ead75667836a6e507c099497639abafe and https://github.com/litex-hub/litex-boards/commit/4a724d9d2d7276e7c18b02d80375afeba43db1e4.
