### ISSUE TITLE
litex_term copy+paste skips characters when pasting

### ISSUE THREAD

**Issue by jeremyherbert** [enjoy-digital/litex#1640]
Hi,

I have found myself repeatedly running `mem_list` in the bios, copying a line in the memory map like `0x20000000 0x800000` and then typing `mem_test <ctrl+shift+v>` to paste the memory region. 

However, I have come across a peculiar issue in that if I use `picocom` to do this it works fine, but it doesn't in `litex_term`. Instead, it randomly skips over characters like this:

```
0x00000800
02000 x000
02000 08000
```

(each line is a separate paste)

I have confirmed by pasting into a separate application that the copy is successful, it's just the paste that has issues.

I am running `litex_term /dev/ttyACM1` and connecting to a `valentyusb` CDC ACM port. `uname -a` is 

```
Linux lattice-xubuntu 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

and I am running on Ubuntu 22.04 with python 3.10.6

**Comment by enjoy-digital** [comment]
Thanks @jeremyherbert for reporting. Do you have the possibility to also do a test with a regular UART? I would first like to see if the issue is also present or if it's specific to ValentyUSB?

**Comment by jeremyherbert** [comment]
I did a test with a regular UART and it works fine. But I also tried to replicate the problem on the orangecrab and it doesn't have the issue. So I am going to close this for now until I can reproduce on more than one piece of hardware.
