### ISSUE TITLE
undefined reference to memtest

### ISSUE THREAD

**Issue by JamesTimothyMeech** [enjoy-digital/litex#1688]
Does anybody have any advice on how to fix this issue: https://github.com/BrunoLevy/learn-fpga/issues/99

I can't tell if `undefined reference to memtest` is an issue with the litex repo or the learn-fpga repo. 

Does anyone have any advice about how I can troubleshoot this?

**Comment by nickoe** [comment]
@JamesTimothyMeech  It looks like you resolved the issue in the issue you link, shouldn't this ticket be closed?

**Comment by JamesTimothyMeech** [comment]
Yes, I will close it now.
