### ISSUE TITLE
Memory block defined by Litex

### ISSUE THREAD

**Issue by ztachip** [enjoy-digital/litex#1700]
I have some RTL code that I am trying to run under Litex framework so that my design is portable between different FPGA. 
But I need to instantiate some dual port memory block.
Does Litex has a way for me to instantiate these dual port memory block so that I dont have to rely on FPGA vector library which would break the portability.
Thanks

**Comment by enjoy-digital** [comment]
Hello @ztachip,

Migen's Memory that is used in LiteX is portable between the different FPGA vendor and can be correctly inferred as dual port BRAM, ex: https://github.com/m-labs/migen/blob/master/examples/basic/memory.py.

You can also search in LiteX project for Memory for more examples. If you don't find a convenient example, I'll try to help you further.

**Comment by ztachip** [comment]
Wow. This is so awesome.
Do you have some links explaining the blocks you have available to help people porting FPGA design?
Im also looking for blocks such as PLL,...
Thanks
Vuong
________________________________

**Comment by enjoy-digital** [comment]
You can find the PLL modules here: https://github.com/enjoy-digital/litex/tree/master/litex/soc/cores/clock and example of use in the LiteX-Boards targets: https://github.com/litex-hub/litex-boards/tree/master/litex_boards/targets

**Comment by enjoy-digital** [comment]
Here is a simple example of code to create a dual port RAM with Migen. You'll then be able to use the read/write ports from your logic.

```python3
from migen import *

class DualPortRAM(Module):
    def __init__(self, width=32, depth=1024):  # defaults to a 32-bit wide, 1024-depth memory block
        self.specials.mem = Memory(width, depth)
        
        # Port 1
        self.specials.wrport1 = self.mem.get_port(write_capable=True, we_granularity=8)
        self.specials.rdport1 = self.mem.get_port(has_re=True)

        # Port 2
        self.specials.wrport2 = self.mem.get_port(write_capable=True, we_granularity=8)
        self.specials.rdport2 = self.mem.get_port(has_re=True)

```

**Comment by ztachip** [comment]
Thanks
