### ISSUE TITLE
The csr.json file is not being generated during Renode installation for Litex

### ISSUE THREAD

**Issue by fdsgdshn** [enjoy-digital/litex#1706]
Hi,

 I came across your webpage that explains how to create litex.repl and litex.resc files to use Litex in [Generate Renode simulation](https://github.com/enjoy-digital/litex/wiki/Generate-Renode-simulation). However, even though I don't receive any errors when entering the commands, the csr.json file is not being generated, and as a result, I cannot obtain these platform and script files. Can you assist me with this issue?

command 1:
python3 litex/boards/targets/arty.py --cpu-type vexriscv --with-ethernet --csr-json csr.json

command 2:

./litex_json2renode.py csr.json \
    --resc litex.resc \
    --repl litex.repl
    --bios-binary soc_ethernetsoc_arty/software/bios/bios.bin

Note: Since the repository is regularly updated, the path does not match the current directory. However, I have already edited it accordingly.

Thanks!

**Comment by enjoy-digital** [comment]
Hi @fdsgdshn,

generating the files now requires adding `--build`. To just generate the files without compiling the design, you can do:
`python3 -m litex_boards.targets.digilent_arty --cpu-type vexriscv --with-ethernet --csr-json csr.json --build --no-compile`

**Comment by fdsgdshn** [comment]
Hi @enjoy-digital ,
Thank you for your response. Yes, as you said, the csr.json file was created with the build parameter, but I think there is a missing part in this file. Because the required platform and script files for Renode are not being generated. The error I'm getting is exactly as follows: csr.json file does not contain the "config_cpu_count" parameter. The error occurs in litex/build/lib/litex/tools/litex_json2renode.py, specifically in line 217, where it tries to access csr['constants']['config_cpu_count'], resulting in a KeyError: 'config_cpu_count'.

**Comment by fdsgdshn** [comment]
This error was fixed. Thanks again for your help!
