### ISSUE TITLE
SoC Appears to no longer fit inside Ice40 FPGA

### ISSUE THREAD

**Issue by JamesTimothyMeech** [enjoy-digital/litex#1707]
I found that the icebreaker example SoC no longer fits in the Ice40: https://github.com/icebreaker-fpga/icebreaker-litex-examples/issues/14

I was told that I should report this to LiteX.

**Comment by enjoy-digital** [comment]
Hi @JamesTimothyMeech,

the design in` icebreaker-fpga` is a bit outdated and Icebreaker support has been based on this and further improved, so I would recommend using it.

I just tested  `python3 -m litex_boards.targets.icebreaker --cpu-type=vexriscv --cpu-variant=lite --build` which build correctly.

**Comment by JamesTimothyMeech** [comment]
Thanks, this one builds without errors!
