### ISSUE TITLE
coremark test of VexRiscv SMP on Sipeed Tang Primer 20K

### ISSUE THREAD

**Issue by BobMa0420** [enjoy-digital/litex#1796]
Hi, I'm running VexRiscv SMP-LINUX on Sipeed Tang Primer 20K with the instruction of [https://github.com/litex-hub/linux-on-litex-vexriscv](url) and I would like to run coremark of it. I'm wondering are there any references for that. Thanks!

**Comment by Variety0820** [comment]
Hello, I am also conducting coremark testing and have obtained the rootfs.cpio file after the same operation. Do you know what kind of operation to continue after obtaining the rootfs.cpio file?
