### ISSUE TITLE
opensbi

### ISSUE THREAD

**Issue by 54o8** [enjoy-digital/litex#1836]
hi，
Why do I get stuck here when I boot linux?
![510cb9f7ad7317b90783becbe8534d0](https://github.com/enjoy-digital/litex/assets/77656720/0d1b91ff-5d9b-4029-814a-ed1cf2fa5848)

**Comment by 54o8** [comment]
![image](https://github.com/enjoy-digital/litex/assets/77656720/6ddd4f07-adcd-47bf-a87d-757f532c194b)

**Comment by enjoy-digital** [comment]
Hi @54o8,

we would probably need more info to be able to help, at least the Board you are using and build command.

**Comment by enjoy-digital** [comment]
Closing since no feedback. @54o8 if you still have trouble, please add following questions to this issue, we'll re-open.
