### ISSUE TITLE
netboot

### ISSUE THREAD

**Issue by 54o8** [enjoy-digital/litex#1846]
hi 
What do I need to do if I use netboot?（tang_primer_20k）
I followed the tutorial to place the files in the image directory into the tfpt directory
![image](https://github.com/enjoy-digital/litex/assets/77656720/a2ea5f79-bd3b-4e43-b6ca-899591143c01)
but netboot failed
![image](https://github.com/enjoy-digital/litex/assets/77656720/db9c5228-5e68-4eaf-9068-a94984890c97)
Do I need to make any changes to the local ip or remote ip

**Comment by enjoy-digital** [comment]
Hi @54o8,

the two IP addresses seems to be on a different subnets, can you first do a test on the same subnet? or test your TFTP server from the same subnet than the FPGA board?

**Comment by enjoy-digital** [comment]
Closing since no feedback. @54o8 if you still have trouble, please add following questions to this issue, we'll re-open.
