### ISSUE TITLE
The non-ASCII character "…" in README.md may cause failure in setup

### ISSUE THREAD

**Issue by cy18** [enjoy-digital/litex#1853]
On my computer, running setup by "./litex_setup.py --init --install" fails with something like UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1334. 

It is caused by the README.md file at the line "Simple cores: RAM, ROM, Timer, UART, JTAG, etc….", where "…" is used instead of normal three dots "...". Replacing it with normal three dots fixes it.

Similar problem is also found in README.md of litex-boards, where the non-ascii characters are "├──"，changing them to “|--” would fix it. 

It's more like an issue of setup.py and locale  language setting. However, since changing README.md is quite simple, I think it would be good to have it changed in the README.md.

**Comment by enjoy-digital** [comment]
Thanks @cy18 for the feedback, this should be fixed with https://github.com/enjoy-digital/litex/commit/33c07a094e7bf257dc34f230c4e9667ea0da0275 and https://github.com/litex-hub/litex-boards/commit/e9dac1e46033b558cbb35903b29c5144e8676aa9.
