### ISSUE TITLE
Windows based build cannot find toolchain support

### ISSUE THREAD

**Issue by briansune** [enjoy-digital/litex#1880]
OSError: Unable to find any of the cross compilation toolchains:
- riscv64-pc-linux-musl
- riscv64-unknown-elf
- riscv64-unknown-linux-gnu
- riscv64-elf
- riscv64-linux
- riscv64-linux-gnu
- riscv-sifive-elf
- riscv64-none-elf
- riscv32-unknown-elf
- riscv32-unknown-linux-gnu
- riscv32-elf
- riscv-none-embed
- riscv-none-elf
-

**Comment by AndrewD** [comment]
You need to install one, this isn't automatic. Litex_setup offers an option to do this

**Comment by briansune** [comment]
@AndrewD 

I changed to Linux platform windows tool-chain is a bit messy.
