### ISSUE TITLE
How to set multi-level sequential trigger in litescope ?

### ISSUE THREAD

**Issue by kevinyuan** [enjoy-digital/litex#1927]
Dear litex team,

I checked the documents but haven't figured out how to set multi-level sequential triggers in litescope, e.g.:

`2 level trigger:  rising edge of (vld & sop) , then  data[3:0] = 0x7`

**Comment by AndrewD** [comment]
Only a single value and mask are supported, this is the logic:
[hit.eq((sink.data & mem.source.mask) == (mem.source.value & mem.source.mask)),](https://github.com/enjoy-digital/litescope/blob/976656b5194db2cdf6c3257c5975e4fa1233f859/litescope/core.py#L83)

**Comment by enjoy-digital** [comment]
Hi @kevinyuan,

as pointed by @AndrewD, this feature is not yet supported in LiteScope.
