### ISSUE TITLE
default FIFO depth for video is too large for some devices

### ISSUE THREAD

**Issue by suarezvictor** [enjoy-digital/litex#1931]
I'm trying to synth on the Lattice ECP5-25F and the default configuration consumes too much BRAM resources (DP16KD cells) as cause of a big FIFO used for video, currently of 65536 entries.

The function "add_video_framebuffer" should have an extra argument to the fifo_depth, as needed by the VideoFramebuffer class, see:
https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/soc.py#L2353

That way some SoC configurations can use less resources and the synthesis can be done. I was able to do that by reducing the FIFO size to 16384.

**Comment by enjoy-digital** [comment]
Thanks for the feedback @suarezvictor, implemented with https://github.com/enjoy-digital/litex/commit/3fa3532f1676fe9da5cc2f78d3265623dd5ba45f.
