### ISSUE TITLE
wiki typo, AXI-Bus.md, R channel description is hard to spot

### ISSUE THREAD

**Issue by aaronferrucci** [enjoy-digital/litex#2041]
Reading the [AXI Bus wiki page](https://github.com/enjoy-digital/litex/wiki/AXI-Bus), at first I thought the R channel (one of my favorites!) was missing. Turns out, it just got embedded in the AR channel description by a wiki syntax typo.

In AXI-Bus.md,
```
*** R (Read Data)**
```
should be
```
* **R (Read Data)**
```
Easy fix, and I'd submit a PR for it, but it doesn't look like that's supported for wikis.

**Comment by AndrewD** [comment]
Thanks, fixed
