### ISSUE TITLE
video console

### ISSUE THREAD

**Issue by uglyoldbob** [enjoy-digital/litex#2088]
It would be nice to have a video terminal for the cpu bios as a configurable option.

**Comment by enjoy-digital** [comment]
Hi @uglyoldbob,

have you look at the `--with-video-terminal` argument of LiteX-Boards targets? This should be doing what you want.

**Comment by uglyoldbob** [comment]
Oh I think it might be because there is no drama configured on my board. Also I accidentally broken the board so this isn't relevant anymore.
