### ISSUE TITLE
board files hosted where?

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litex#224]
https://github.com/litex-hub/litex-boards

I am wondering WHERE is the proper official location of litex board files? is the litex-hub or here at litex github?

**Comment by enjoy-digital** [comment]
Hi @AnttiLukats,

the boards/platforms directly in LiteX the ones used for development and regression testing. The official location for board files is in https://github.com/litex-hub/litex-boards

**Comment by AnttiLukats** [comment]
ok case closed, I assumed that way
