### ISSUE TITLE
bios build on win32

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litex#227]
when compiling software there is error:

C:\Python34 -m litex.soc.software.mkmscimg bios.bin --little
process_begin: CreateProcess(NULL, C:\Python34 -m litex.soc.software.mkmscimg bios.bin --little, ...) failed.

where does litex get "C:\Python34 ??

python is in C:\Python37

surprising everything else except the msmscimg thing seem to work..

OK, this can be fixed by adding manually
set python=c:\python37\python.exe to environment

but somehow the litex scripts can not find the correct python by itself.. while pretty much everything else python related stuff works without issues

**Comment by enjoy-digital** [comment]
It seems by default `python3` is pointing to  _C:\Python34_ on your machine (LiteX is calling mkmscimg with this https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/common.mak#L4, not _C:\Python34_ directly), can you make sure that in a terminal, python3 is pointing to a valid python3 interpreter?

**Comment by AnttiLukats** [comment]
I got it working with extra env setting, what made me wonder was: fusesoc worked with no issues, litex MOSTLY worked as well.. so I guess litex could also work out of box without extra env settings..

anyway, I got litex to build full vexriscv on s7mini board and it worked immediatly, and that compiled on true win32 w7 machine, no linux layer anywhere..

pretty impressed, litex was a bit work on w32 but is now fully working, fusesoc did look like EASY but fails with some weird jinja template not found issue, so litex is leading 1:0 right now
