### ISSUE TITLE
Option to change toolchain path?

### ISSUE THREAD

**Issue by GuzTech** [enjoy-digital/litex#23]
I'm trying to build Arty-SoC but I'm getting an error that the Xilinx tools were not found in /opt/Xilinx/Vivado which makes sense because I installed it at $HOME/Software/Xilinx/Vivado. Other than changing the hardcoded path, is there a way to point to a different toolchain path on the command line as an argument?

**Comment by mithro** [comment]
Try `-Ob toolchain_path $XILINX_DIR/opt/Xilinx/` ?

**Comment by GuzTech** [comment]
@mithro Where should I put those arguments?

I tried `make arty_minisoc -Ob toolchain_path /home/guztech/Software/Xilinx/` in the arty-soc repo, and `sudo python3.5 setup.py develop -Ob toolchain_path /home/guztech/Software/Xilinx/` in the litex repo, but none of them worked.

**Comment by mithro** [comment]
@GuzTech Sorry for the red herring, it doesn't look like arty-soc has support for these options out of the box.

@GuzTech You might want to take a look at our [`make.py`](https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/make.py) which allows you to use those options like that.

**Comment by enjoy-digital** [comment]
@GuzTech: I'm closing this since this is related to https://github.com/enjoy-digital/arty-soc repo, please re-open one there if you still need it.
