### ISSUE TITLE
changing RISCV toolchain prefix?

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litex#236]
hi
I am currently manually patching vexriscv/core.py

    @property
    def gcc_triple(self):
       return ("riscv64-unknown-elf", "riscv32-unknown-elf")
       return ("riscv-none-embed", "riscv-none-embed")

each time I update LiteX as riscv-none-embed is the only easy to install risc-v mainstream c compiler with pre-compiled binaries for win platform, 

is there an easier way to override the compiler prefix? I think it may be a useful feature to have a possibility to override the core provided compiler, could be something like ENV setting, or whatever method that would avoid eternal patching..

**Comment by enjoy-digital** [comment]
You will no longer have to patch with https://github.com/enjoy-digital/litex/commit/e670cb91767f564dffc38b40de53b8133a70f858 :)
