### ISSUE TITLE
TCL for Diamond wrong \ /

### ISSUE THREAD

**Issue by AnttiLukats** [enjoy-digital/litex#238]
top.tcl generated for diamond on win platform should have / and NOT \ as path separator, on win platform

**Comment by enjoy-digital** [comment]
@AnttiLukats: can you check if https://github.com/enjoy-digital/litex/commit/cc607f022a7ebbf41803c49426ce4ab58d350d68 solves the issue?

**Comment by enjoy-digital** [comment]
Closing, @AnttiLukats please re-open https://github.com/enjoy-digital/litex/commit/cc607f022a7ebbf41803c49426ce4ab58d350d68 was not solving it.
