### ISSUE TITLE
Unable to build without cpu

### ISSUE THREAD

**Issue by xobs** [enjoy-digital/litex#268]
With 6fcb12a98f6d9df67c5c0390194fc755a300d18f, it is no longer possible to build without a CPU.

Specifically, this line unconditionally accesses `self.cpu.data_width` even if `self.cpu is None`: https://github.com/enjoy-digital/litex/commit/6fcb12a98f6d9df67c5c0390194fc755a300d18f#diff-5b5aa398d41ddd6086fbe51e97931f5cR249

**Comment by enjoy-digital** [comment]
Sorry for not catching that, i added a test for this case to the CI and fixed this case.
