### ISSUE TITLE
Unable to use SPRAM as main ram

### ISSUE THREAD

**Issue by xobs** [enjoy-digital/litex#364]
As of 42efa998269ebdeaa07c9d8b9b4bda25f9aecc20 it is no longer possible to use the ICE40UP5K "SPRAM" as main RAM.

What we do is specify `integrated_sram_size=0`, then add a block after the init with:

```python
        spram_size = 128*1024
        self.submodules.spram = up5kspram.Up5kSPRAM(size=spram_size)
        self.register_mem("spram", self.mem_map["spram"], self.spram.bus, spram_size)
```

However, with 42efa998269ebdeaa07c9d8b9b4bda25f9aecc20 the value is implicitly replaced with `0x1000`, causing a Wishbone SRAM to be added.

**Comment by enjoy-digital** [comment]
Sorry, this behavior has been reverted with https://github.com/enjoy-digital/litex/commit/7bc34a9bc75ce0b5d672323c7d05797592697274.
