### ISSUE TITLE
Unable to import RemoteClient. 

### ISSUE THREAD

**Issue by teezzan** [enjoy-digital/litex#377]
Hello,
I was learning how to use Litex by using the examples given at 
https://github.com/litex-hub/fpga_101 
While running lab3, I found out that I couldn't run the python scripts because the console could not import RemoteClient.
The error was
`ModuleNotFoundError : No module named 'litex.soc.tools'`
What do I need to do?
Thanks,
Taiwo

**Comment by enjoy-digital** [comment]
Hello @teezzan,

thanks for reporting. This has just been fixed with https://github.com/litex-hub/fpga_101/commit/058bc9d6b11f104d46d3b500dd050ee3dffb8590. Free free to open issues on https://github.com/litex-hub/fpga_101 directly if you have others issues.
