### ISSUE TITLE
Change IP adress in simulation

### ISSUE THREAD

**Issue by BracketMaster** [enjoy-digital/litex#388]
192.168.1.100 is under my router's subnet and BSD kernel refuses to let me touch it as long as WiFi is on.
Is there a way to change the destination IP address in sim. I somehow changed it in hardware months ago for ECP5…

``--remote-ip`` for ``sim.py`` [here](https://github.com/litex-hub/linux-on-litex-vexriscv) is not a valid argument.

Also, changing the following does nothing in simulation:
https://github.com/enjoy-digital/litex/blob/18a9d4ff2f2d0c85e55ccc6686b502e54a065f2b/litex/tools/litex_sim.py#L303-L304

**Comment by enjoy-digital** [comment]
This is now possible with https://github.com/enjoy-digital/litex/commit/aebaea7764e3eba2332bbd56b8fa5107ebea4417.
