### ISSUE TITLE
Manually exiting litex_term breaks shell

### ISSUE THREAD

**Issue by felixheld** [enjoy-digital/litex#46]
When exiting litex_term with ctrl-c the terminal gets corrupted until reset is run which fixes the terminal again. Or am I just missing some proper mechanism to exit litex_term? When unplugging the board, litex_term exits without breaking the shell.

**Comment by enjoy-digital** [comment]
Fixed via https://github.com/enjoy-digital/litex/commit/e7d1683e34a56167be9e48614657ae69d1d7895e.
