### ISSUE TITLE
Broken build with "serv" CPU & Vivado 2019.02

### ISSUE THREAD

**Issue by ozbenh** [enjoy-digital/litex#497]
Using litex-boards/targets/arty.py --cpu-type="serv" gives me errors from Vivado when hitting the generated .v files from LiteX such as:

ERROR: [Synth 8-6735] net type must be explicitly specified for 'serial_rx' when default_nettype is none [/home/benh/hackplace/litex/litex-boards/litex_boards/targets/soc_basesoc_arty/gateware/top.v:6]

This seems to be caused by the fact that serv source files have a `default_nettype none at the top of each file, which Vivado carries over to other .v files.

I'm working around it by modifying serv locally to restore the nettype at the end of each file, but ideally LiteX should either generate explicit "wire" statements in module definitions or change the default back at the top of each generated .v file.

**Comment by enjoy-digital** [comment]
Thanks for reporting, this is fixed with https://github.com/enjoy-digital/litex/commit/b0578580714ad7d298e244fc3835c06ba082f2c1.
