### ISSUE TITLE
CSRStorage not reset on soft reboot

### ISSUE THREAD

**Issue by madscientist159** [enjoy-digital/litex#577]
I have noticed that any CSRStorage objects declared with a reset= value (e.g. `self.config = CSRStorage(size=32, reset=0x12345678`) will only be reset to that value on initial FPGA configuration.  Running a soft reset of the CPU (`reboot`) leaves the CSRStorage registers at the prior values from before the reboot.

This has caused some degree of problems when e.g. a new peripheral core is now coming up in an unknown (operational / post-config) state after a soft reboot, and the bootloader can't handle (re)configuration from that state.  Is there a known / preferred method to ensure the CSRStorage registers are reset on soft CPU reboot?

**Comment by enjoy-digital** [comment]
The `reboot` command of the BIOS is indeed currently only reseting the CPU and not the peripherals. We could change this behavior, in the meantime, the `soc.ctrl.reset`could be connected the `CRG` to reset the full SoC.

**Comment by madscientist159** [comment]
@enjoy-digital What is the correct method to attach `soc.ctrl.reset` to the `CRG`?

**Comment by enjoy-digital** [comment]
You could add a `reset` signal to the CRG and do in the SoC : `self.comb += self.crg.reset.eq(self.ctrl.reset)`.

**Comment by enjoy-digital** [comment]
The` reboot` command is now doing a full reset of the SoC with: https://github.com/enjoy-digital/litex/commit/ffc554deded2990c89dc66f12ce8e2755a7414fe and https://github.com/litex-hub/litex-boards/commit/2b17dc1b89894facc34495f783d670df351fd090.
