### ISSUE TITLE
Command aliases are missing following installation instructions

### ISSUE THREAD

**Issue by ghent360** [enjoy-digital/litex#596]
Downloaded litex_setup.py and run
./litex_setup.py init install --user

Then
./litex_setup.py gcc

lxsim command is not available, neither is lxterm (actually lxterm is a different binary in ubuntu). I figured these are aliases to python scripts in litex/litex/tools/ Is there something missing from the install process? these should be installed as aliases in the shell somehow.

**Comment by mithro** [comment]
@ghent360 Did the output complain about not having `~/.local/bin` not in your `$PATH`?

**Comment by ghent360** [comment]
Perhaps it did, but I have not noticed it. I would politely suggest you add a reminder in the README.md instructions.
Also in ubuntu and probably other distros there is /usr/bin/lxterm binary, which is a wrapper around xterm, perhaps renaming the alias would be warranted.

**Comment by ghent360** [comment]
@mithro Thank you for the help.
