### ISSUE TITLE
Import the opensparc t2 core

### ISSUE THREAD

**Issue by GunnerG** [enjoy-digital/litex#628]
https://www.oracle.com/servers/technologies/opensparc-t2-page.html

**Comment by daveshah1** [comment]
This would be quite good fun as a large place and route benchmark on one of the big Xilinx boards!

**Comment by enjoy-digital** [comment]
Closing since this will probably not happen in the short future (no available time/resources currently to work on this), but happy to discuss and re-open if someone wants to explore this.
