### ISSUE TITLE
SDRAM_PHY_MODULES undeclared compiling risc-v BIOS

### ISSUE THREAD

**Issue by ghent360** [enjoy-digital/litex#646]
go to litex_boards/targets
run ./colorlight_5a_75x.py no arguments.

Error:
make: Entering directory 'xxx/fpga/liteX/litex-boards/litex_boards/targets/build/colorlight_5a_75b/software/liblitedram'
 CC       sdram.o
xxx/fpga/liteX/litex/litex/soc/software/liblitedram/sdram.c: In function 'sdrmpr':
xxx/fpga/liteX/litex/litex/soc/software/liblitedram/sdram.c:909:23: error: 'SDRAM_PHY_MODULES' undeclared (first use in this function); did you mean 'SDRAM_PHY_PHASES'?
  for(module=0; module<SDRAM_PHY_MODULES; module++) {
                       ^~~~~~~~~~~~~~~~~
                       SDRAM_PHY_PHASES

**Comment by enjoy-digital** [comment]
Thanks for reporting, this is fixed with https://github.com/enjoy-digital/litex/commit/c247814ed4e81cbaf15cb76cccf3260d39f16743.
