### ISSUE TITLE
CSRs generated in a loop don't reach csr.csv

### ISSUE THREAD

**Issue by BrettRD** [enjoy-digital/litex#658]
I have a module that captures a bunch of data on multiple channels, and I'd like to present them to wishbone-tool on sequentially named `CSRStatus` registers.

When I declare a list of `CSRStatus` objects in a list, they don't make it to the final build.
```
        # this doesn't appear in csr.csv
        self.output = [CSRStatus(8, name='channel_'+str(chan)) for chan in range(channels)]
```

```
    # only the last channel appears in csr.csv
        self.output = []
        for chan in range(channels):
            self.tmp = CSRStatus(8, name='channel_'+str(chan))
            self.output.append(self.tmp)
```

If I (ab)use exec to declare a bunch of sequentially named variables, each assigned one `CSRStatus`, and then put those intermediate variables into a list, they appear in csr.csv just fine.

Is there a way of generating CSR registers without assigning a named variable to them?
Is there a way of naming subsets of large CSRs instead?

**Comment by enjoy-digital** [comment]
@BrettRD: there are indeed some limitations, but the following should work:

````python3
self.output = []
for chan in range(channels):
    tmp = CSRStatus(8, name='channel_'+str(chan))
    self.output.append(tmp)
    setattr(self, f"tmp{chan}", tmp)
````

**Comment by BrettRD** [comment]
Thanks! it works!
So setattr here generates module member variables whose names are defined by a simple f-string, and sets their values to the new CSR registers.
The object reference is held by self.output so it can be iterated over, and the object reference also exists as a module named variable so it gets picked up later in the chain.
