### ISSUE TITLE
Add Ibex as supported CPU

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex#695]
It would be good to support the Ibex - https://github.com/lowRISC/ibex

**Comment by mithro** [comment]
Antmicro will probably look at this...

FYI -- @kgugala / @mgielda / @pgielda

**Comment by enjoy-digital** [comment]
Initial support has been added quite easily with https://github.com/enjoy-digital/litex/commit/510bda4c9939f9f025c278e2d04214fe8d6769b6 since interfaces are very similar to CV32E40P:
https://twitter.com/enjoy_digital/status/1361276610972966913

We'll now need to add interrupt support and create a `pythondata-cpu-ibex` package.

**Comment by mithro** [comment]
@enjoy-digital - I'll take on creating the `pythondata-cpu-ibex` package

**Comment by mithro** [comment]
WIP at https://github.com/litex-hub/pythondata-cpu-ibex

**Comment by mithro** [comment]
This should now be published at https://pypi.org/project/pythondata-cpu-ibex/

**Comment by enjoy-digital** [comment]
Thanks @mithro, we also need OpenTitan: https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/ibex/core.py#L205-L209, is it also possible to include it in the repo?

**Comment by mithro** [comment]
I created [`pythondata-misc-opentitan`](https://github.com/litex-hub/pythondata-misc-opentitan) see https://pypi.org/search/?q=pythondata-misc-opentitan

It appears this also includes Ibex at [`pythondata_misc_opentitan/resources/hw/vendor/lowrisc_ibex/rtl/`](https://github.com/litex-hub/pythondata-misc-opentitan/tree/master/pythondata_misc_opentitan/resources/hw/vendor/lowrisc_ibex/rtl) and things [like the hmac RTL at `pythondata_misc_opentitan/resources/hw/ip/hmac/rtl`](https://github.com/litex-hub/pythondata-misc-opentitan/tree/master/pythondata_misc_opentitan/resources/hw/ip/hmac/rtl)

I called it `misc` because I assume that people like @xobs and @bunnie might want to use the non-CPU RTL parts?

**Comment by mateusz-holenko** [comment]
FYI: We created a demo running the LiteX BIOS on LiteX/Ibex platform in Renode: https://github.com/renode/renode/blob/c150b382854ff515464220c945a36823a9589536/scripts/single-node/litex_ibex.resc

**Comment by enjoy-digital** [comment]
@mateusz-holenko: Nice, thanks for sharing.

**Comment by enjoy-digital** [comment]
Initial Ibex support has been added and pythondata package created. We can close this now and will open specific issues for others points when useful.
