### ISSUE TITLE
Fails to build bios with --with-ethernet flag

### ISSUE THREAD

**Issue by CBJamo** [enjoy-digital/litex#74]
sniped output of `arty.py --cpu-type picorv32 --with-ethernet`

```
`macadr' referenced in section `.text' of boot.o: defined in discarded section `.sdata' of boot.o
`macadr' referenced in section `.text' of boot.o: defined in discarded section `.sdata' of boot.o
`broadcast' referenced in section `.text' of ../libnet/libnet.a(microudp.o): defined in discarded section `.sdata' of ../libnet/libnet.a(microudp.o)
`broadcast' referenced in section `.text' of ../libnet/libnet.a(microudp.o): defined in discarded section `.sdata' of ../libnet/libnet.a(microudp.o)

```

This can be fixed by moving the line: `*(.sdata .sdata.* .gnu.linkonce.s.*)` from the discard section to the text section of the linker script. Poking around in the history of the linker script, it looks like data sections are undesireable. I'm not sure why that is the case, or if this is breaking whatever rule or design goal was behind that.

**Comment by enjoy-digital** [comment]
Thanks for reporting and sorry for the delay. This is fixed by: https://github.com/enjoy-digital/litex/commit/85308672d396111a07c70e0704c5c4191826d4ac
