### ISSUE TITLE
litex_json2dts.py: Has hard coded initrd settings that are too small

### ISSUE THREAD

**Issue by stffrdhrn** [enjoy-digital/litex#748]
The settings for initrd are hard coded in the dts generator script as below, this gives only 8mb for the OpenRISC linux rootfs, which is too small.  It would be nice if we could pass sizes in via the command like. For example:  `--initrd-start 0x00800000 --initrd-size 1234567`, the values hard coded now in the script can be used as fall back defaults.

https://github.com/enjoy-digital/litex/blob/bddb170650242e3f993b882806474ca3480a6a7c/litex/tools/litex_json2dts.py#L34-L42

**Comment by stffrdhrn** [comment]
@mateusz-holenko

**Comment by mateusz-holenko** [comment]
@stffrdhrn Sounds like a good idea to me, added some comments to #749.

**Comment by enjoy-digital** [comment]
Thanks @stffrdhrn, @mateusz-holenko for looking at this. The dicts were just added to avoid breaking mork1x support  when merging VexRiscv SMP, being able to configure this while keeping current default values also sounds like a good idea to me.

**Comment by enjoy-digital** [comment]
https://github.com/enjoy-digital/litex/pull/749 has been merged, thanks @stffrdhrn, @mateusz-holenko.
