### ISSUE TITLE
Remove boards directory and directly rely on LiteX-Boards

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litex#760]
Maintaining local boards no longer seems to useful and generates more work than the advantages it was initially providing. Relying directly on [LiteX-Boards](https://github.com/litex-hub/litex-boards) would simplify things.

**Comment by mithro** [comment]
+1 - Sounds great to me!

**Comment by enjoy-digital** [comment]
This has been done with https://github.com/enjoy-digital/litex/commit/f31f9a20f0b9134af25e08d1d768c72bc07e473f and imports have been replaced in the cores that were relying on `litex.boards` (mostly for the examples/benches).
