### ISSUE TITLE
produce colorful wiring diagrams to visualize the generated SoC

### ISSUE THREAD

**Issue by hansfbaier** [enjoy-digital/litex#766]
Qsys on altera produces a nice graphical representation of the SoC that is being built.
It would be great to have a generator that produces a nice wiring block diagram (eg in SVG)
which makes it possible to understand how all the modules are wired together.

**Comment by enjoy-digital** [comment]
@hansfbaier: I'm moving this to https://github.com/enjoy-digital/litex/issues/769 that is an issue we can now use to discuss ideas for the project without creating specific issues for them initially.
