### ISSUE TITLE
litex_term cpu load

### ISSUE THREAD

**Issue by sergpolkin** [enjoy-digital/litex#767]
**litex_term** do 100% load one cpu core
possible solve is change:
https://github.com/enjoy-digital/litex/blob/16008d3f3a493b081bd25c97fc1f2d64b55016c4/litex/tools/litex_term.py#L499
`while True: time.sleep(0.1)`

**Comment by enjoy-digital** [comment]
Thanks, fixed with https://github.com/enjoy-digital/litex/commit/19fda3364ae1e2c96a77331fb19c4b8efd56d927.
