### ISSUE TITLE
jtagbone: `litex_client --read` outputs mangled register values on nexys4ddr

### ISSUE THREAD

**Issue by gsomlo** [enjoy-digital/litex#802]
Reproducer:
1. Apply [nexys4ddr-analyzer-jtag.patch.txt](https://github.com/enjoy-digital/litex/files/5932258/nexys4ddr-analyzer-jtag.patch.txt) to `litex_boards`, then
2. build a LiteX SoC like this:
```
        litex-boards/litex_boards/targets/nexys4ddr.py --build \
                --cpu-type rocket --cpu-variant linux --sys-clk-freq 50e6 \
                --with-ethernet --with-sdcard --integrated-rom-size 0x10000 \
                --with-analyzer --csr-csv ./csr.csv
```
3. start `litex_server`:
```
        litex_server --jtag --jtag-config litex-boards/litex_boards/prog/openocd_xc7_ft2232.cfg
```
4. modify the scratch register using `litex_client` (YMMV on the address `0x12000004`, depending on whether you built a LiteX+Rocket SoC or something else):
```
        litex_client --write 0x12000004 0xffff1234
````
5. on the SoC's console, at the BIOS prompt, verify that the value was written correctly:
```
litex> mem_read 0x12000004
Memory dump:
0x12000004  34 12 ff ff                                      4...            
````
6. attempt to read the value via `litex_client`:
```
        litex_client --read 0x12000004
```

Expected result: `litex_client` will output `0xffff1234`
Actual result: `litex_client` outputs `0xc3bfc3bf`

This also works correctly if using other bridge types (e.g. uartbone or etherbone). Only broken on reads (writes work fine, as evidenced by the ability to see them successfully take hold via the bios prompt and `mem_read`) and only broken when using `jtagbone`. Only tested on `nexys4ddr` using Rocket.

**Comment by enjoy-digital** [comment]
@gsomlo: I just tested it and haven't been able to reproduce the issue (while I remember being able to do so in the past).
