### ISSUE TITLE
litex/soc/cores/cpu/vexriscv_smp/* files are not included in the egg installation

### ISSUE THREAD

**Issue by hansfbaier** [enjoy-digital/litex#804]
When building linux on vexriscv compilation fails because the said files are missing
in the egg. Manually copying them into the egg installation directory makes compilation succeed.

**Comment by enjoy-digital** [comment]
Thanks for the feedback @hansfbaier, this was probably related to outdated MANIFEST.in, would you mind trying with https://github.com/enjoy-digital/litex/commit/b485829ec44b3a17e8034872b33fc4c883e2cda6?

**Comment by hansfbaier** [comment]
@enjoy-digital  Works well now, thanks!

**Comment by enjoy-digital** [comment]
Thanks.
