### ISSUE TITLE
Please link/mention the wiki as "documentation" in the README

### ISSUE THREAD

**Issue by thirtythreeforty** [enjoy-digital/litex#812]
Hello! I've been enjoying using LiteX and climbing the learning curve. After a couple weeks of getting started I finally discovered the wiki which nicely explains a lot of the concepts I had worked out by reading LiteX code.

In my opinion the wiki is under-advertised! I know there's currently a link in the readme, but it's for "projects" and doesn't really sound like it's documentation. I think adding an explicit mention with the keyword "documentation" would help future newcomers find it (I actually Ctrl-F for `doc` when I land on a new project!).

**Comment by enjoy-digital** [comment]
Hello @thirtythreeforty,

This indeed seems obvious now that you are reporting it..., thanks for this fresh look and feedback! This has been added with https://github.com/enjoy-digital/litex/commit/3b00a7c4fe5ece9048f5db4c97c994bf9d50c86b.
