### ISSUE TITLE
lxsim --cpu-type=vexriscv command not found in MacOS X 

### ISSUE THREAD

**Issue by jhu960213** [enjoy-digital/litex#835]
Hello,

I'm just following the installation guide and everything seems to be working up until the last point where I want to simulate in verilator. All the packages have been installed with brew and it works but when I type this command in I get "zsh: command not found: lxsim". Is this a package issue or I'm not including something in my path for the command etc? Thanks! 

I'm running MacOS X 10.15.7

Best,
J.H

**Comment by enjoy-digital** [comment]
Hello @jhu960213,

lxsim is part of the console scripts installed with LiteX: https://github.com/enjoy-digital/litex/blob/master/setup.py#L36-L51

Until we figure out why it's not available after the installation on your machine, you can find the script in litex.tools.litex_sim.

**Comment by jhu960213** [comment]
Hello @enjoy-digital ,

I actually was able to find lxsim as the binary itself was in Library/Python/3.8/bin/ folder and I executed the binary with the full path. During the build phase, it ran into some errors. Attached below are my outputs of the error. 
<img width="1680" alt="Screen Shot 2021-03-01 at 8 13 20 PM" src="https://user-images.githubusercontent.com/20133323/109728882-0c2bdc80-7b85-11eb-96ec-8957199eaa57.png">
<img width="1680" alt="Screen Shot 2021-03-01 at 8 13 44 PM" src="https://user-images.githubusercontent.com/20133323/109728884-0c2bdc80-7b85-11eb-8150-63e2757deb32.png">

Let me know if this is enough for troubleshooting what is going on? Thanks! 

Best,
J.H

**Comment by enjoy-digital** [comment]
@jhu960213: Your issue has probably been fixed with https://github.com/enjoy-digital/litex/commit/d3407c67b189d2c338766febb3bf2c57f6f80d1d, could you update and try?

**Comment by marrrk** [comment]
> Hello @jhu960213,
> 
> lxsim is part of the console scripts installed with LiteX: https://github.com/enjoy-digital/litex/blob/master/setup.py#L36-L51
> 
> Until we figure out why it's not available after the installation on your machine, you can find the script in litex.tools.litex_sim.

Hi, I received the same error (command not found) after following all the installation steps. I'm not running Mac OS however, I'm running POP OS 20.04. Using this comment I was able to run the simulation just fine.

**Comment by enjoy-digital** [comment]
Sorry the issue seems specific to your installation, other MacOS X user have been able to use LiteX on their machine. You probably resolved the issue so I'm closing but feel free to re-open if that's not the case, we'll try to have help from a MacOS user.
