### ISSUE TITLE
Can't install LiteX properly on Ubuntu16.04

### ISSUE THREAD

**Issue by jimmymagemtek** [enjoy-digital/litex#837]
Hi Sir,
I found the following error message when installing LtieX on Ubuntu16.04:

root@jimmy-VirtualBox:~/LiteX# ./litex_setup.py init install --user
[checking litex_setup.py]...
[installing migen]...
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running develop
running egg_info
writing migen.egg-info/PKG-INFO
writing dependency_links to migen.egg-info/dependency_links.txt
writing requirements to migen.egg-info/requires.txt
writing top-level names to migen.egg-info/top_level.txt
reading manifest file 'migen.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'migen.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python3.6/site-packages/migen.egg-link (link to .)
migen 0.9.2 is already the active version in easy-install.pth

Installed /root/LiteX/migen
Processing dependencies for migen==0.9.2
Searching for colorama==0.4.4
Best match: colorama 0.4.4
Processing colorama-0.4.4-py3.6.egg
colorama 0.4.4 is already the active version in easy-install.pth

Using /root/.local/lib/python3.6/site-packages/colorama-0.4.4-py3.6.egg
Finished processing dependencies for migen==0.9.2
[installing nmigen]...
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running develop
running egg_info
writing nmigen.egg-info/PKG-INFO
writing dependency_links to nmigen.egg-info/dependency_links.txt
writing entry points to nmigen.egg-info/entry_points.txt
writing requirements to nmigen.egg-info/requires.txt
writing top-level names to nmigen.egg-info/top_level.txt
writing manifest file 'nmigen.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python3.6/site-packages/nmigen.egg-link (link to .)
nmigen 0.3.dev243+gf7c2b94 is already the active version in easy-install.pth
Installing nmigen-rpc script to /root/.local/bin

Installed /root/LiteX/nmigen
Processing dependencies for nmigen==0.3.dev243+gf7c2b94
Searching for importlib_resources; python_version < "3.9"
Reading https://pypi.python.org/simple/importlib_resources/
Best match: importlib-resources 5.1.1
Downloading https://files.pythonhosted.org/packages/32/36/a380aecd01d0db4a73f95167906a1f99afdffb965b3cd5e634e124e45436/importlib_resources-5.1.1.tar.gz#sha256=563c5579cd40a7d5c6256ea6519b510152b6968103ab540b9771a50093a09056
Processing importlib_resources-5.1.1.tar.gz
Writing /tmp/easy_install-8ua3v_rv/importlib_resources-5.1.1/setup.cfg
Running importlib_resources-5.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8ua3v_rv/importlib_resources-5.1.1/egg-dist-tmp-d0wkvuzs
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Removing /root/.local/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg
Moving UNKNOWN-0.0.0-py3.6.egg to /root/.local/lib/python3.6/site-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /root/.local/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg
error: The 'importlib_resources; python_version < "3.9"' distribution was not found and is required by nmigen
Traceback (most recent call last):
  File "./litex_setup.py", line 171, in <module>
    subprocess.check_call("python3 setup.py develop --user", shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python3 setup.py develop --user' returned non-zero exit status 1.

It seems  that "importlib" install fails.
What can I do to finish the installation ?
Please advise. Many thanks.

Jimmy

**Comment by nickoe** [comment]
It clearly says that:
> error: The 'importlib_resources; python_version < "3.9"' distribution was not found and is required by nmigen

This means that your default python version is too old, and that is probably expected when you are using ubuntu 16.04. I would personally recommend you to upgrade to something like ubuntu 20.04 which should have python3 installed as default if you want to play around with litex. You may be able to install a newer version on ubuntu 16.04 as well
