### ISSUE TITLE
Knowing about timing violations?

### ISSUE THREAD

**Issue by alanvgreen** [enjoy-digital/litex#851]
We're using Vivado and Radiant for various projects. Is there a simple way to make a LiteX build "fail" when timing constraints are not met?

Before we set up our own wrapper scripts to grep the timing report files in the gateware build directory, I was wondering if there might be something in litex already. If not, what is best practice?

**Comment by enjoy-digital** [comment]
Hi @alanvgreen,

we have this feature for some build backends (timingstrict build parameter on icestorm/trellis for example) but  this is not generalized to all backends so still indeed has to be checked manually.

**Comment by alanvgreen** [comment]
Thanks of the quick response!
