### ISSUE TITLE
Add `description` field to soc.svd

### ISSUE THREAD

**Issue by xobs** [enjoy-digital/litex#862]
The SVD description format appears to require a `description` tag that litex does not currently supply. This means that tools such as Renode do not accept it:

```
There was an error executing command 'sysbus ApplySVD @D:\Code\Xous\Core\emulation\renode.svd'
Field 'description' in 'SOC' is required.
```

Litex should generate a `description` field when it produces the SVD file, even if it's blank.

**Comment by enjoy-digital** [comment]
Hi @xobs, @bunnie,

I think this has been implemented through https://github.com/enjoy-digital/litex/pull/880, can we close this issue?

**Comment by xobs** [comment]
Yes, it works for me thanks!
