### ISSUE TITLE
There is no module containing RemoteClient  available under soc folder on GitHub source

### ISSUE THREAD

**Issue by jimmymagemtek** [enjoy-digital/litex#889]
Hi Sir,
I know that this issue is discussed on issue #377, but currently, there is indeed no source code available under soc folder on Github.

Where can I get it? Please provide the path. Thanks.

Jimmy

**Comment by enjoy-digital** [comment]
Hello @jimmymagemtek,

RemoteClient source code is here: https://github.com/enjoy-digital/litex/blob/master/litex/tools/litex_client.py#L21

**Comment by jimmymagemtek** [comment]
Hi Sir,
Thanks.

Jimmy
