### ISSUE TITLE
Nexus: PrjOxide: workaround for SDR I/O registers 

### ISSUE THREAD

**Issue by tcal-x** [enjoy-digital/litex#907]
Related to https://github.com/YosysHQ/nextpnr/issues/698.

Until that issue is resolved, there should be a special version of `common.lattice_NX_special_overrides` used when toolchain=oxide, that maps SDRInput to FD1P3BX instead of IFD1P3BX, and maps SDROutput to FD1P3BX instead of OFD1P3BX.

fyi @gatecat

**Comment by danc86** [comment]
This is hampering our ability to work on our Crosslink-NX-based product with nextpnr. I'm too much of a noob to try and fix this in nextpnr itself, so I had a go at adding this suggested workaround in PR #987.
