### ISSUE TITLE
VexRiscv Minimal variant won't boot

### ISSUE THREAD

**Issue by jedrzejboczar** [enjoy-digital/litex#937]
Initially, the problem was wrong `cdelay` in simulation wiht the "minimal" variant of VexRiscv as described here: https://github.com/enjoy-digital/litedram/issues/255#issuecomment-857634957.

I wanted to measure the delays on real hardware, so I applied the following patch: [measure-cdelay.zip](https://github.com/enjoy-digital/litex/files/6629969/measure-cdelay.zip) and built for the Arty target. The execution stops after printing `Measure:`. When using variant "lite" everything works fine and the elapsed time is printed. 

Then I reverted the patch and just built with all defaults using:
```
python litex-boards/litex_boards/targets/digilent_arty.py --cpu-variant minimal --load --build
```
and the execution stops after the line `BIOS built on Jun 10 2021 11:04:03`, so on the `crcbios();` and there is no more output.

**Comment by enjoy-digital** [comment]
@jedrzejboczar: I just tested it and it works correctly. The possible issue was probably that the BIOS required a full rebuild do to the fact that Minimal variant only supports `rv32i`. With https://github.com/enjoy-digital/litex/commit/44b223a9182318d58b9d4249d879f925dfd11e7d, the BIOS will now automatically be fully rebuilt in this case.
