### ISSUE TITLE
Auto-generated soc.h incompatible with assembly files.

### ISSUE THREAD

**Issue by JosephBushagour** [enjoy-digital/litex#966]
Issue: The auto-generated `soc.h` file cannot be included in any assembly code because the access functions aren't hidden behind a pre-processor conditional. This makes conditional assembling based in things like `CONFIG_CPU_HAS_INTERRUPT` and `CONFIG_CPU_VARIANT` currently not possible.
```C
// in file asssembly.S
#include "generated/soc.h"
// results in: Error: unrecognized opcode `static inline int config_clock_frequency_read(void){'
```

Proposed change: Place access functions behind a `#ifndef LITEX_SOC_DEFINES_ONLY`. Users can then include the file in any assembly code by defining (and then undefining) `LITEX_SOC_DEFINES_ONLY`. Because this is an "opt-out" system, it won't break existing code.
```C
// in file asssembly.S
#define LITEX_SOC_DEFINES_ONLY
#include "generated/soc.h"
#undef LITEX_SOC_DEFINES_ONLY
// results in: all defines visible in the assembly
```

**Comment by enjoy-digital** [comment]
Thanks @JosephBushagour for identifying and removing this limitation, your #967 PR has been merged.
