### ISSUE TITLE
SPI Flash memory region not `cached` when using LiteSPI.

### ISSUE THREAD

**Issue by JosephBushagour** [enjoy-digital/litex#981]
First of all, great work with LiteSPI integration it's been incredibly helpful!

I noticed in the new changes in `litex/soc/integration/soc.py` that when using the old `add_spi_flash` call the SoCRegion has no kwarg for `cached` and thus the default value of `True` is used. Line in question:
https://github.com/enjoy-digital/litex/blob/14d60661b9a06ae092d3ee81fed5833db094d4dd/litex/soc/integration/soc.py#L1501

However, when using the new call to `add_spi_flash` with LiteSPI the `cached` kwarg is specifically set to `False`. Line in question:
https://github.com/enjoy-digital/litex/blob/14d60661b9a06ae092d3ee81fed5833db094d4dd/litex/soc/integration/soc.py#L1521

This results in spiflash memory region being considered `io` in the generated `csr.csv` file only when using LiteSPI. Is there a reason for this? Would it be possible to add an override in the `add_spi_flash` call that lets us consider this region `cached`?

**Comment by JosephBushagour** [comment]
Thanks!

**Comment by enjoy-digital** [comment]
Thanks @JosephBushagour for the feedback. I also run into this while testing on some targets, this is fixed with https://github.com/enjoy-digital/litex/commit/f0a258e0a7f3e1d6625526bef32d239c8ba5aa79.
