### ISSUE TITLE
Wishbone version

### ISSUE THREAD

**Issue by navaneeth-cirel** [enjoy-digital/litex#999]
Hi,

I am trying to find some info on the current implementation of Wishbone bus in LiteX, so far I could not find any docs related to this. I am looking for the following :
1. Wishbone spec version ?
2. Handshake protocol - Standard or Pipelined ?
3. WISHBONE Registered Feedback - supported ?

So far after going through the [wishbone.py](https://github.com/enjoy-digital/litex/blob/master/litex/soc/interconnect/wishbone.py) what I could gather is that it implements Wishbone 4 classic with standard handshaking protocol with asynchronous feedback, it will be good if someone can confirm this.

In general I think it will good to have this info mentioned somewhere either in the source file or in Wiki.

**Comment by enjoy-digital** [comment]
Hi @navaneeth-cirel,

`wishbone.py` implements wishbone classic with standard handshaking and synchronous feedback. We'll indeed indicate this in the code or/and wiki.

**Comment by navaneeth-cirel** [comment]
Hi @enjoy-digital ,

Thank you for confirming that, is there any plan on supporting the Wishbone pipelined mode and the advanced registered feedback ?

**Comment by enjoy-digital** [comment]
We are planning to support bursts now that we start seing bottlenecks on different systems due to lack of it.

**Comment by navaneeth-cirel** [comment]
Thank you for that info.

I am currently working on adding a wishbone master and a slave in my LiteX project, if it is fine I would like to add a small overview on how to do it in the wiki, might be helpful for other first timer developers.

**Comment by enjoy-digital** [comment]
@navaneeth-cirel: Sure, that's one of the Wiki page I was planning to create, feel free to initiate one (as a Github issue or Wiki page), this would be a nice contribution. The Wishbone version has been added to wishbone.py with https://github.com/enjoy-digital/litex/commit/bbcbe51bf308040cbfcd40acb5fad3470ee67a34.

**Comment by navaneeth-cirel** [comment]
@enjoy-digital thank you for that.
I will start an issue then where we can review and then move it into the wiki.
